<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Laser" Id="{5724ed8c-95a4-443b-8d0a-229c2f523827}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Laser
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[LaserD := ( ReallaserD - laserSetPoint);



]]></ST>
    </Implementation>
    <LineIds Name="Laser">
      <LineId Id="9" Count="3" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>